# Generated by Django 5.0.1 on 2024-02-08 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 25, 43, 95841, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
