# Generated by Django 5.0.1 on 2024-02-08 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_course_alter_payment_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 21, 7, 102614, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
