# Generated by Django 5.0.1 on 2024-03-01 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_payment_payment_status_payment_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 7, 14, 19, 914549, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='unpaid', verbose_name='Статус оплаты'),
        ),
    ]
