# Generated by Django 5.0.1 on 2024-03-01 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_payment_session_payment_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 10, 32, 55, 527161, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
